config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'bundles#index', as: :home

  resources :bundles do
    resources :bookings, only: [:new, :create]
    resources :items, except: [:index, :show, :edit, :update]
    resources :reviews, only: [:new, :create, :show, :edit, :update, :destroy]

    collection do
      get 'mybundles', to: 'bundles#mybundles', as: :mybundles
    end
  end

  resources :bookings, only: [:index, :show] do
    member do
      patch 'approve', to: 'bookings#approve', as: :approve
      patch 'deny', to: 'bookings#deny', as: :deny
    end
  end
end

app/views/shared/_flash.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/shared/_formbooking.html.erb
<%= simple_form_for [@bundle, @booking] do |f| %>

  <%= f.input :start_date, required: true, input_html: { data: { provide: 'datepicker', 'date-format': 'dd/mm/yyyy' } }, as: :string %>
  <%= f.input :end_date, required: true, input_html: { data: { provide: 'datepicker', 'date-format': 'dd/mm/yyyy' } }, as: :string %>
  <%#= f.input :shipping_address, placeholder: "Put your Full Address Here" %>
  <%= f.input :comment, as: :text, input_html: {rows: 10, cols: 10}, placeholder: "Add a comment for the Bundle-Owner"  %>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <%= f.submit "Request Bundle", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/shared/_formbundle.html.erb
<div class="container">
  <div class="col-xs-6 col-xs-offset-3">
    <div class="form">
      <h1 class="text-center"><%= title %></h1>
      <%= simple_form_for @bundle do |f| %>
        <%= f.input :name, required: true, autofocus: true, placeholder: 'Enter bundle name...', label: false, hint: '30 characters maximum' %>
        <%= f.input :gender, required: true, autofocus: true, collection: Bundle.gender %>
        <%= f.input :age_group, required: true, autofocus: true, collection: Bundle.age_groups %>
        <%= f.input :price_per_day, label: "Set a price per day" %>
        <%= f.input :description, required: true, autofocus: true, as: :text, input_html: {rows: 10, cols: 10}, placeholder: "Tell us about your bundle...", label: false  %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.submit "Create New Bundle", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_list_bundle_cards.html.erb
<div class="container" id="bundles-list">
    <div class="row">
      <% if @bundles.empty? %>
        <div class="container">
          <p>We don't have any bundles matching your search yet.  I'm sure others would love it too... why not <%= link_to 'add a bundle', new_bundle_path %>, or search for something else! </p>
        </div>
      <% else %>
        <% @bundles.each do |bundle| %>
        <% if policy(bundle).show? %>
          <div class="col-xs-6 col-md-3">
            <%= link_to bundle_path(bundle) do %>
              <div class="bundles-card">
                <div class="bundle-image" style="background-image:url(<%= cl_image_path bundle.photo.url(:bundle_card) unless bundle.photo.blank? %>)">
                </div>
                <div class="bundle-content">
                  <div class="bundle-name">
                    <h5 class="text-bold bundle-title"><%= bundle.name.titleize %></h5>
                    <% if bundle.gender == "Male" %>
                      <p><i class="fas fa-mars"></i></p>
                    <% else %>
                      <p><i class="fas fa-venus"></i></p>
                    <% end %>
                  </div>
                </div>
                <div class="bundle-info">
                  <p class="bundle-age"> <%= bundle.age_group %> </p>
                  <p class="bundle-items"><i class="fas fa-tshirt"></i> <%= bundle.number_of_items %></p>
                  <p class="bundle-price"><i class="fas fa-dollar-sign"> </i><%= bundle.price_per_day_formatted %> </p>
                </div>
                <div class="rating">
                  <p>
                  <% bundle.average_rating.to_i.times do %>
                    <span class="glyphicon glyphicon-star rating"></span>
                  <% end %>
                  <% bundle.blank_stars.times do %>
                    <span class="glyphicon glyphicon-star-empty rating"></span>
                  <% end %>
                  (<%= bundle.number_of_reviews %>)
                  </p>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
        <% end %>
      </div>
      <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to bundles_path, class: 'navbar-wagon-brand' do %>
    <%= cl_image_tag("bluepacifier.png") %>
  <% end %>
  <!-- Right Navigation -->
  <div class="navbar-right hidden-xs hidden-sm">
    <p><%= link_to "Home", bundles_path, class: "navbarlink" %></p>
    <% if policy(Booking).show? %>
    <% if user_signed_in? %>
      <p><%= link_to "Bookings", bookings_path, class: "navbarlink" %></p>
    <% end %>
    <% end %>


    <% if user_signed_in? %>
      <% unless current_user.bundles.nil? %>
        <p><%= link_to "My Bundles", mybundles_bundles_path, class: "navbarlink" %></p>
      <% end %>
      <p><%= link_to "Add Bundle", new_bundle_path, class: "navbarlink" %></p>
    <% else %>
      <p><%= link_to "Login",  new_user_session_path, class: "navbarlink" %></p>
    <% end %>

    <!-- Profile picture with dropdown list -->
    <% if user_signed_in? %>
      <div class="navbaritem">
        <div class="dropdown">
          <!-- Load default image if Cloudinary image doesn't exist -->
          <% if current_user.photo.file.nil? %>
            <%= image_tag "default-avatar-min.jpg", class: 'avatar dropdown-toggle', id: 'navbar-wagon-menu', data: { toggle: 'dropdown'} %>
          <% else %>
            <%= cl_image_tag current_user.photo, height: 35, width: 35, class: 'avatar dropdown-toggle', id: 'navbar-wagon-menu', data: { toggle: 'dropdown' } %>
          <% end %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li><%= link_to "Home", home_path, class: "navbarlink" %></li>
            <% if user_signed_in? %>
              <li><%= link_to "Bookings", bookings_path, class: "navbarlink" %></li>
              <li><%= link_to "Dashboard", bookings_path, class: "navbarlink" %></li>
            <% end %>

            <% if user_signed_in? %>
              <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
            <% end %>
          </ul>
        </div>
      </div>
    <% end %>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "Home", home_path, class: "navbarlink" %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Bookings", bookings_path, class: "navbarlink" %></li>
          <li><%= link_to "Dashboard", bookings_path, class: "navbarlink" %></li>
        <% end %>

        <% if user_signed_in? %>
          <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_table.html.erb
<h2 class="text-center"><%= title %></h2>
<div class="table-header">
  <p class="table-bundle-name">Bundle Name</p>
  <p class="table-bundle-user">User</p>
  <p class="table-bundle-email">Email</p>
  <p class="table-bundle-dates">Dates</p>
  <p class="table-bundle-days">Days</p>
  <p class="table-bundle-price">Price</p>
</div>
<% bookings.each do |booking| %>
  <div class="table-row">
    <div class="table-item-name">
      <p><%= booking.bundle.name %></p>
    </div>
    <div class="table-img">
      <% if booking.user.photo.file.nil? %>
        <%= image_tag 'default-avatar-min.jpg', class: 'avatar' %>
      <% else %>
        <%= cl_image_tag booking.user.photo, height: 35, width: 35, class: 'avatar' %>
      <% end %>
    </div>

    <div class="table-user">
      <p><%= "#{booking.user.first_name} #{booking.user.last_name}" %></p>
    </div>

    <div class="table-email">
      <p><%= booking.user.email %></p>
    </div>

    <div class="table-dates">
      <p><%= booking.start_date.strftime('%a, %b %d %Y') %></p>
      <p><%= booking.end_date.strftime('%a, %b %d %Y') %></p>
    </div>

    <div class="table-days">
      <p><%= booking.days %></p>
    </div>

    <div class="table-total-price">
      <p>$<%= booking.price_formatted %></p>
    </div>

    <div class="table-approve">
      <% if booking.pending_booking? %>
        <%= link_to 'Approve', approve_booking_path(booking), method: :patch, class: 'booking-approve btn-approve' %>
      <% end %>
    </div>

    <div class="table-deny">
      <% if booking.pending_booking? %>
        <%= link_to 'Deny', deny_booking_path(booking), method: :patch, class: 'booking-deny btn-deny' %>
      <% end %>
    </div>

    <% if booking.current_booking? %>
      <div class="table-status current">
        <p><i class="fas fa-user-check"></i>  Current Booking</p>
      </div>
    <% elsif booking.future_booking? %>
      <div class="table-status future">
        <p><i class="fas fa-user-plus"></i>  Future Booking</p>
      </div>
    <% elsif booking.past_booking? %>
      <div class="table-status past">
        <p><i class="fas fa-user-clock"></i>  Past Booking</p>
      </div>
    <% end %>
  </div>
<% end %>