config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'bundles#index', as: :home

  resources :bundles do
    resources :bookings, only: [:new, :create]
    resources :items, except: [:index, :show, :edit, :update]
    resources :reviews, only: [:new, :create, :show, :edit, :update, :destroy]

    collection do
      get 'mybundles', to: 'bundles#mybundles', as: :mybundles
    end
  end

  resources :bookings, only: [:index, :show] do
    member do
      patch 'approve', to: 'bookings#approve', as: :approve
      patch 'deny', to: 'bookings#deny', as: :deny
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :set_bundle, only: [:new, :create, :destroy]
  before_action :set_booking, only: [:create]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.bundle = @bundle
    @review.booking = @booking
    @review.user = current_user
    if @review.save
      respond_to do |format|
        format.html { redirect_to bundle_path(@bundle) }
        format.js  # <-- will render `app/views/reviews/create.js.erb`
      end
    else
      respond_to do |format|
        format.html { render 'bundle_path(@bundle' }
        format.js  # <-- idem
      end
    end
  end

  def edit
  end

  def update
  end

  def destroy
    authorize @review
    @review.destroy
  end

  private

  def review_params
    params.require(:review).permit(:title, :content, :stars, :bundle_id)
  end

  def set_bundle
    @bundle = Bundle.find(params[:bundle_id])
  end

  def set_review
    @review = Review.find(params[:id])
  end

  def set_booking
    @booking = current_user.bookings.where(bundle_id: params[:bundle_id]).first
  end

end

app/views/reviews/_form.html.erb
<%= simple_form_for [bundle, review], remote: true do |f| %>
  <%= f.input :title %>
  <%= f.input :content, as: :text, input_html: {rows: 10, cols: 5}, placeholder: "Add a review"  %>
  <%= f.input :stars, collection: [ 1, 2, 3, 4, 5 ]  %>
  <%= f.submit "Add Review", class: "btn btn-primary" %>
<% end %>

app/views/reviews/_review.html.erb
  <div class="review_card" data-review-id="<%= review.id %>">
    <h5 class="bold"><%= review.title %></h5>
    <%= review.content %>
    <p> -  <%= review.user.first_name.capitalize %></p>
    <hr>
    <div class="review_stars">
      <div class="stars">
        <% review.stars.times do %>
        <i class="fas fa-star"></i>
        <% end %>
      </div>
       <%= link_to bundle_review_path(@bundle, review), method: :delete, remote: true do %>
          <i class="fas fa-trash-alt"></i>
        <% end %></div>
    </div>

app/views/reviews/_show.html.erb
<hr>
<div class="reviews" >
  <div class="review_form">
    <% if @can_i_review %>
      <%= render 'reviews/form', bundle: @bundle, review: Review.new %>
    <% end %>
  </div>
  <div class="past_reviews" id="jsreview">
    <% unless @bundle.reviews.nil? %>
      <% @bundle.reviews.each do |review| %>
      <%= render 'reviews/review', review: review %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/reviews/_starscard.html.erb
<% if @bundle.averagereview == 0.5 %>
  <i class="fas fa-star-half"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>
<% elsif @bundle.averagereview == 1.0 %>
  <i class="fas fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>
<% elsif @bundle.averagereview == 2.0 %>
  <i class="fas fa-star"></i><i class="fas fa-star-half"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>
<% elsif @bundle.averagereview == 2.5 %>
  <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>
<% elsif @bundle.averagereview == 3.0 %>
  <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star-half"></i><i class="far fa-star"></i><i class="far fa-star"></i>
<% elsif @bundle.averagereview == 3.5 %>

<% elsif @bundle.averagereview == 4.0 %>
<% elsif @bundle.averagereview == 4.5 %>
<% elsif @bundle.averagereview == 5.0 %>
<% end %>

app/views/reviews/create.js.erb
function refreshForm(innerHTML) {
  const newReviewForm = document.getElementById('new_review');
  newReviewForm.innerHTML = innerHTML;
}

function addReview(reviewHTML) {
  const reviews = document.getElementById('jsreview');
  reviews.insertAdjacentHTML('beforeend', reviewHTML);
}

<% if @review.errors.any? %>
  refreshForm('<%= j render "reviews/form", review: @review, bundle: @bundle   %>');
<% else %>
  addReview('<%= j render "reviews/review", review: @review %>');
  refreshForm('<%= j render "reviews/form", review: Review.new, bundle: @bundle %>');
<% end %>

app/views/reviews/destroy.js.erb
document.querySelector("[data-review-id='<%= @review.id %>']").remove();